/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: ../sanity.schema.json
export type InfoSection = {
  title: string
  items?: Array<
    {
      _key: string
    } & HeroInfoItem
  >
}

export type AnimationReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'animation'
}

export type SanityFileAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
}

export type AnimationSection = {
  _type: 'animationSection'
  title?: string
  animation?: Array<{
    animation: AnimationReference
    backgroundVideo?: {
      asset?: SanityFileAssetReference
      media?: unknown
      _type: 'file'
    }
    _key: string
  }>
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type PhotoInfoGalleryItem = {
  _type: 'photoInfoGalleryItem'
  name?: string
  role?: string
  location?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type PhotoInfoGallery = {
  _type: 'photoInfoGallery'
  title: string
  items?: Array<
    {
      _key: string
    } & PhotoInfoGalleryItem
  >
}

export type CompanyInfoColumn = {
  _type: 'companyInfoColumn'
  firstColumnText: BlockContent
  secondColumnText: BlockContent
  thirdColumnText: BlockContent
}

export type CompanyInfo = {
  _type: 'companyInfo'
  centerText: string
  hoverCenterText: string
  items?: Array<
    {
      _key: string
    } & CompanyInfoColumn
  >
}

export type TextWithBackgroundColor = {
  _type: 'textWithBackgroundColor'
  backgroundColor: '#FCC554' | '#373B45' | '#000000'
  about?: string
}

export type CampaignReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'campaign'
}

export type CampaignSection = {
  _type: 'campaignSection'
  campaign: CampaignReference
  backgroundVideo?: {
    asset?: SanityFileAssetReference
    media?: unknown
    _type: 'file'
  }
}

export type Gallery = {
  _type: 'gallery'
  items?: Array<
    {
      _key: string
    } & GalleryItem
  >
}

export type GalleryItem = {
  _type: 'galleryItem'
  type: 'photo' | 'video'
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  thumbnail?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  vimeoUrl?: string
}

export type HeroInfoItem = {
  _type: 'heroInfoItem'
  title: string
  text: string
}

export type ProjectHero = {
  _type: 'projectHero'
  backgroundColor: '#FCC554' | '#373B45' | '#000000' | '#707E69' | '#18181B' | '#8C7E79'
  title?: string
  subtitle?: string
  about?: string
  infoSection?: InfoSection
}

export type Video = {
  _type: 'video'
  vimeoUrl?: string
}

export type DocumentariesReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'documentaries'
}

export type ProjectSection = {
  _type: 'projectSection'
  title?: string
  documentaries?: Array<{
    documentaries: DocumentariesReference
    backgroundVideo?: {
      asset?: SanityFileAssetReference
      media?: unknown
      _type: 'file'
    }
    _key: string
  }>
}

export type Link = {
  _type: 'link'
  linkType?: 'href' | 'email' | 'project' | 'animation' | 'campaign'
  href?: string
  email?: string
  documentaries?: DocumentariesReference
  animation?: AnimationReference
  campaign?: CampaignReference
  openInNewTab?: boolean
}

export type BlockContentTextOnly = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
  listItem?: 'bullet' | 'number'
  markDefs?: Array<{
    href?: string
    _type: 'link'
    _key: string
  }>
  level?: number
  _type: 'block'
  _key: string
}>

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        linkType?: 'href' | 'email' | 'project'
        href?: string
        email?: string
        documentaries?: DocumentariesReference
        openInNewTab?: boolean
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }
  | {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
      _key: string
    }
>

export type Animation = {
  _id: string
  _type: 'animation'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  client?: string
  backgroundVideo?: {
    asset?: SanityFileAssetReference
    media?: unknown
    _type: 'file'
  }
  animationBuilder?: Array<
    | ({
        _key: string
      } & Video)
    | ({
        _key: string
      } & ProjectHero)
    | ({
        _key: string
      } & Gallery)
    | ({
        _key: string
      } & CompanyInfo)
  >
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type Campaign = {
  _id: string
  _type: 'campaign'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  backgroundVideo?: {
    asset?: SanityFileAssetReference
    media?: unknown
    _type: 'file'
  }
  campaignBuilder?: Array<
    | ({
        _key: string
      } & Video)
    | ({
        _key: string
      } & ProjectHero)
    | ({
        _key: string
      } & Gallery)
    | ({
        _key: string
      } & CompanyInfo)
  >
}

export type ContactPage = {
  _id: string
  _type: 'contactPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  backgroundVideo?: {
    asset?: SanityFileAssetReference
    media?: unknown
    _type: 'file'
  }
  contactBuilder?: Array<
    | ({
        _key: string
      } & Video)
    | ({
        _key: string
      } & ProjectHero)
    | ({
        _key: string
      } & Gallery)
    | ({
        _key: string
      } & CompanyInfo)
    | ({
        _key: string
      } & TextWithBackgroundColor)
    | ({
        _key: string
      } & PhotoInfoGallery)
  >
}

export type AboutPage = {
  _id: string
  _type: 'aboutPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  aboutBuilder?: Array<
    | ({
        _key: string
      } & Video)
    | ({
        _key: string
      } & ProjectHero)
    | ({
        _key: string
      } & Gallery)
    | ({
        _key: string
      } & TextWithBackgroundColor)
    | ({
        _key: string
      } & CompanyInfo)
    | ({
        _key: string
      } & PhotoInfoGallery)
  >
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type Settings = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      linkType?: 'href' | 'project'
      href?: string
      documentaries?: DocumentariesReference
      openInNewTab?: boolean
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    metadataBase?: string
    _type: 'image'
  }
}

export type Documentaries = {
  _id: string
  _type: 'documentaries'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  client?: string
  backgroundVideo?: {
    asset?: SanityFileAssetReference
    media?: unknown
    _type: 'file'
  }
  documentariesBuilder?: Array<
    | ({
        _key: string
      } & Video)
    | ({
        _key: string
      } & ProjectHero)
    | ({
        _key: string
      } & Gallery)
    | ({
        _key: string
      } & CompanyInfo)
  >
}

export type SanityAssistInstructionTask = {
  _type: 'sanity.assist.instructionTask'
  path?: string
  instructionKey?: string
  started?: string
  updated?: string
  info?: string
}

export type SanityAssistTaskStatus = {
  _type: 'sanity.assist.task.status'
  tasks?: Array<
    {
      _key: string
    } & SanityAssistInstructionTask
  >
}

export type SanityAssistSchemaTypeAnnotations = {
  _type: 'sanity.assist.schemaType.annotations'
  title?: string
  fields?: Array<
    {
      _key: string
    } & SanityAssistSchemaTypeField
  >
}

export type SanityAssistOutputType = {
  _type: 'sanity.assist.output.type'
  type?: string
}

export type SanityAssistOutputField = {
  _type: 'sanity.assist.output.field'
  path?: string
}

export type AssistInstructionContextReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'assist.instruction.context'
}

export type SanityAssistInstructionContext = {
  _type: 'sanity.assist.instruction.context'
  reference: AssistInstructionContextReference
}

export type AssistInstructionContext = {
  _id: string
  _type: 'assist.instruction.context'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  context?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type SanityAssistInstructionUserInput = {
  _type: 'sanity.assist.instruction.userInput'
  message: string
  description?: string
}

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<
    | {
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }
    | ({
        _key: string
      } & SanityAssistInstructionFieldRef)
    | ({
        _key: string
      } & SanityAssistInstructionContext)
    | ({
        _key: string
      } & SanityAssistInstructionUserInput)
  >
  style?: 'normal'
  listItem?: never
  markDefs?: null
  level?: number
  _type: 'block'
  _key: string
}>

export type SanityAssistInstructionFieldRef = {
  _type: 'sanity.assist.instruction.fieldRef'
  path?: string
}

export type SanityAssistInstruction = {
  _type: 'sanity.assist.instruction'
  prompt?: SanityAssistInstructionPrompt
  icon?: string
  title?: string
  userId?: string
  createdById?: string
  output?: Array<
    | ({
        _key: string
      } & SanityAssistOutputField)
    | ({
        _key: string
      } & SanityAssistOutputType)
  >
}

export type SanityAssistSchemaTypeField = {
  _type: 'sanity.assist.schemaType.field'
  path?: string
  instructions?: Array<
    {
      _key: string
    } & SanityAssistInstruction
  >
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | InfoSection
  | AnimationReference
  | SanityFileAssetReference
  | AnimationSection
  | SanityImageAssetReference
  | PhotoInfoGalleryItem
  | PhotoInfoGallery
  | CompanyInfoColumn
  | CompanyInfo
  | TextWithBackgroundColor
  | CampaignReference
  | CampaignSection
  | Gallery
  | GalleryItem
  | HeroInfoItem
  | ProjectHero
  | Video
  | DocumentariesReference
  | ProjectSection
  | Link
  | BlockContentTextOnly
  | BlockContent
  | Animation
  | Slug
  | Campaign
  | ContactPage
  | AboutPage
  | SanityImageCrop
  | SanityImageHotspot
  | Settings
  | Documentaries
  | SanityAssistInstructionTask
  | SanityAssistTaskStatus
  | SanityAssistSchemaTypeAnnotations
  | SanityAssistOutputType
  | SanityAssistOutputField
  | AssistInstructionContextReference
  | SanityAssistInstructionContext
  | AssistInstructionContext
  | SanityAssistInstructionUserInput
  | SanityAssistInstructionPrompt
  | SanityAssistInstructionFieldRef
  | SanityAssistInstruction
  | SanityAssistSchemaTypeField
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: sanity/lib/queries.ts
// Variable: settingsQuery
// Query: *[_type == "settings"][0]
export type SettingsQueryResult = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      linkType?: 'href' | 'project'
      href?: string
      documentaries?: DocumentariesReference
      openInNewTab?: boolean
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    metadataBase?: string
    _type: 'image'
  }
} | null

// Source: sanity/lib/queries.ts
// Variable: getProjectQuery
// Query: *[_type == 'project' && slug.current == $slug][0]{    _id,    _type,    name,    slug,    heading,    subheading,    "projectBuilder": projectBuilder[]{      ...,    },  }
export type GetProjectQueryResult = null

// Source: sanity/lib/queries.ts
// Variable: sitemapData
// Query: *[_type == "project" && defined(slug.current)] | order(_type asc) {    "slug": slug.current,    _type,    _updatedAt,  }
export type SitemapDataResult = Array<never>

// Source: sanity/lib/queries.ts
// Variable: projectsSlugs
// Query: *[_type == "project" && defined(slug.current)]  {"slug": slug.current}
export type ProjectsSlugsResult = Array<never>

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == "settings"][0]': SettingsQueryResult
    '\n  *[_type == \'project\' && slug.current == $slug][0]{\n    _id,\n    _type,\n    name,\n    slug,\n    heading,\n    subheading,\n    "projectBuilder": projectBuilder[]{\n      ...,\n    },\n  }\n': GetProjectQueryResult
    '\n  *[_type == "project" && defined(slug.current)] | order(_type asc) {\n    "slug": slug.current,\n    _type,\n    _updatedAt,\n  }\n': SitemapDataResult
    '\n  *[_type == "project" && defined(slug.current)]\n  {"slug": slug.current}\n': ProjectsSlugsResult
  }
}
